### ISSUE TITLE
Super interesting to know more

### ISSUE THREAD

**Issue by jstetic** [SonicRift/Vestaboard#1]
Hey Shane.  Is this the vestaboard you are talking about https://www.vestaboard.com/?  If so I'd be really interesting in working on this project with you.

**Comment by SonicRift** [comment]
Hi! Apologies for the late response here, somehow I missed your message! I would love the help, absolutely! You're correct that it is for that platform.
Vestaboard just made some changes to how their API works, and so I have basically restarted from scratch. Feel free to fork and send a PR for any changes or updates you've got!

**Comment by SonicRift** [comment]
Got a basic framework going after Vestaboard's changes - ready to get rolling on it! @jstetic, let me know if you have ideas or suggestions - all for it!
