### ISSUE TITLE
Allow passing in Installable and subscriptionId to Board

### ISSUE THREAD

**Issue by robbiet480** [SonicRift/Vestaboard#10]
I'd like to be able to pass in only `Installable` and `subscriptionId` to `Board`. That would allow me to initialize a `Board` without having to choose between using `self.subscriptionId` in `Installable` or having to provide `apiKey`, `apiSecret` and `subscriptionId` to `Board`.

**Comment by SonicRift** [comment]
Good idea, I will add this into version 0.4.1 along with some bug fixes and enhancements I’m working on!
