### ISSUE TITLE
Support of vestaboard simulator

### ISSUE THREAD

**Issue by guenter-ms** [SonicRift/Vestaboard#7]
Hi SonicRift,

I like your project and the vestaboard at all: Very cool!

And I like to propose to support a way to feed a vestaboard browser based simulator like this: https://simulator.vestaboard.com

Or is that already possible to call that page with or without your API? 

Would be very helpful especially for testing.

Many greetings from Germany, we got 50cm of snow....

Thank you for an answer,
best Guenter.

**Comment by SonicRift** [comment]
Good morning! Hope you are enjoying the snow!

To answer your question, yes this is already supported with this wrapper! All you need is your Installable's API key and API Secret and for it to be installed on that particular board via Vestaboard's portal.

I'm assuming you already know this, so posting for others who may not know: You can display a particular board by passing in the board ID as a URL param like this:
`https://simulator.vestaboard.com/?disableAnimation=0&amp;boardId=put-your-board-ID-here`
(These also currently work in an `<iframe>` if you'd like to embed in a website)

Once you have that set up, it's a matter of creating an instance of `Installable()` and pass that into a new `Board()`. Let me know if it gives you any issues!

Shane

**Comment by guenter-ms** [comment]
Hi Shane!

Thank you for fast reply and the good news!

I signed in at vestaboard and couldt compose some messages. And so I got the url’s with the boardIDs to see the result in the simulator. Fine!

But there was no way to get/request the API key and secret. Do I need to buy a vestaboard first? I’m at the step to evaluate before buying. 

Thank you for clarification / hint on this.

Guenter. 

Am 10.02.2021 um 14:03 schrieb Shane Sutro <notifications@github.com>:


Good morning! Hope you are enjoying the snow!

To answer your question, yes this is already supported with this wrapper! All you need is your Installable's API key and API Secret and for it to be installed on that particular board via Vestaboard's portal.

I'm assuming you already know this, so posting for others who may not know: You can display a particular board by passing in the board ID as a URL param like this:
https://simulator.vestaboard.com/?disableAnimation=0&amp;boardId=put-your-board-ID-here
(These also currently work in an <iframe> if you'd like to embed in a website)

Once you have that set up, it's a matter of creating an instance of Installable() and pass that into a new Board(). Let me know if it gives you any issues!

Shane

**Comment by SonicRift** [comment]
Ah, I see what you're saying!
So you'll need to create a new installable on the Vestaboard portal first to get your keys!

Here's what you do:
- [ ] Go to https://web.vestaboard.com and sign in. 
- [ ] On the left, choose `Developers`
- [ ] Click the `Create new installable` button and give it a name
- [ ] Click the `Create your first API Credential` button. This is where you associate the installable with a particular board (physical or electronic/simulated)
- [ ] Save/store your `API Key` and `API Secret` in a safe place

That's it from Vestaboard's side of things. 
Now in your code, create an instance of Installable:
```python
import vestaboard

installable = vestaboard.Installable('your api key', 'your api secret') # This will get and store your Subscriber ID, which you will also need

vboard = vestaboard.Board(installable)

#Done! Now you can call methods on vboard to post to your simulator:
vboard.post('Seize the day!')
```

Let me know how it goes or if you need more help!

Shane

**Comment by guenter-ms** [comment]
Thank you!

I got the keys and can now move forward. Because I (and other readers?) are not hardcore developers, it would be very helpful for some more installation hints. 

Is that javascript code you sent below? Can you provide an easy script which can run on a raspi or mac? That would make the breakthrough.

I also tried on an raspi:

pi@raspberrypi:~ $ pip install vestaboard
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vestaboard
  Could not find a version that satisfies the requirement vestaboard (from versions: )
No matching distribution found for vestaboard
pi@raspberrypi:~ $ 

Also very helpful would be to provide your API on nodered.org <http://nodered.org/> e.g.: https://flows.nodered.org/node/node-red-contrib-tts-ultimate <https://flows.nodered.org/node/node-red-contrib-tts-ultimate>
Then everyone can put the API credentials in the config-node and your methods can be exposed by different nodes like „Post message“ or „Raw message“ without any need for coding and programming.
I use nodered to integrate everything in my home (lights, blinds, sonos, hue, TV, Weatherdata, Calendar,…). 
And then: !!! Everyone would be able to integrate everything and every information with vestaboard messages. 

OK, was only a idea to think about….

Thanks again for supporting!!

Guenter
 

Am 10.02.2021 um 16:01 schrieb Shane Sutro <notifications@github.com>:


Ah, I see what you're saying!
So you'll need to create a new installable on the Vestaboard portal first to get your keys!

Here's what you do:

 Go to https://web.vestaboard.com <https://web.vestaboard.com/> and sign in.
 On the left, choose Developers
 Click the Create new installable button and give it a name
 Click the Create your first API Credential button. This is where you associate the installable with a particular board (physical or electronic/simulated)
 Save/store your API Key and API Secret in a safe place
That's it from Vestaboard's side of things.
Now in your code, create an instance of Installable:

import vestaboard

installable = vestaboard.Installable('your api key', 'your api secret') # This will get and store your Subscriber ID, which you will also need

vboard = vestaboard.Board(installable)

#Done! Now you can call methods on vboard to post to your simulator:
vboard.post('Seize the day!')
Let me know how it goes or if you need more help!

Shane

**Comment by SonicRift** [comment]
Totally understand what you're saying! I'll certainly consider adding that documentation, although that does have more to do with Vestaboard's portal and less to do with this software.
Still, any tips and tricks are always useful!

The code is not JavaScript, it's Python - you should be able to copy/paste just that script above and run it (obviously you'll need to swap out the arguments with your own actual API Key and API Secret to get it to work.

Not sure why it's not being found with pip, but I suspect it has to do with how you're calling `pip`. This package is only available for Python >= 3.6. I believe that `pip` defaults to the Python 2 version of the installer. Since Python 2.x is not supported, that may be why it's not finding it. Try running it with `pip3` instead like this:
`pip3 install --upgrade vestaboard`
This should work on Mac or Raspi, but I will check on my own raspi and see if there's a problem with that.

I haven't done anything with nodered, but it sounds interesting! I'll add that as a feature request and look into that! Thanks for the suggestion. Do let me know if installing with `pip3` works or if it's still erroring and I will open an issue.

**Comment by guenter-ms** [comment]
OK!

That works:

pi@raspberrypi:~ $ pip3 install vestaboard
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vestaboard
  Downloading https://files.pythonhosted.org/packages/01/d4/34ab21cb913fedd2202d38a7c1bbf70fc1592520fc124f47effe5277f557/Vestaboard-0.3.1-py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from vestaboard) (2.21.0)
Installing collected packages: vestaboard
Successfully install
ed vestaboard-0.3.1
pi@raspberrypi:~ $ 


Then I tried this:

pi@raspberrypi:~/.local/lib/python3.7/site-packages $ ls
importapi.py  pythonapitest.py  vestaboard  Vestaboard-0.3.1.dist-info
pi@raspberrypi:~/.local/lib/python3.7/site-packages $ python importapi.py
Traceback (most recent call last):
  File "importapi.py", line 1, in <module>
    import vestaboard
  File "/home/pi/.local/lib/python3.7/site-packages/vestaboard/__init__.py", line 60
    raise ValueError(f'Nested items must be lists, not {type(row)}.')
                                                                   ^
SyntaxError: invalid syntax
pi@raspberrypi:~/.local/lib/python3.7/site-packages $ 

The only statement in file importapi.py file is „import vestaboard“

Don’t hit me…

Guenter


Am 10.02.2021 um 18:02 schrieb Shane Sutro <notifications@github.com>:


Totally understand what you're saying! I'll certainly consider adding that documentation, although that does have more to do with Vestaboard's portal and less to do with this software.
Still, any tips and tricks are always useful!

The code is not JavaScript, it's Python - you should be able to copy/paste just that script above and run it (obviously you'll need to swap out the arguments with your own actual API Key and API Secret to get it to work.

Not sure why it's not being found with pip, but I suspect it has to do with how you're calling pip. This package is only available for Python >= 3.6. I believe that pip defaults to the Python 2 version of the installer. Since Python 2.x is not supported, that may be why it's not finding it. Try running it with pip3 instead like this:
pip3 install --upgrade vestaboard
This should work on Mac or Raspi, but I will check on my own raspi and see if there's a problem with that.

I haven't done anything with nodered, but it sounds interesting! I'll add that as a feature request and look into that! Thanks for the suggestion. Do let me know if installing with pip3 works or if it's still erroring and I will open an issue.

**Comment by SonicRift** [comment]
Gotcha, we're getting closer!
I just verified on my own Raspberry Pi, and it's definitely to do with the whole Python 2 vs Python 3 thing.

That error you got is regarding that string format. Python's so-called "f-strings" are only supported in Python 3, and it looks like you're running it with Python 2. Just like you needed to specify `pip3` instead of `pip`, you also need to call the script with `python3` not `python`.
Make sure when you're running your file you specify that it should be run with Python 3 as follows:

`pi@raspberrypi:~ $ _python3 importapi.py_`

Thank you for bringing these to my attention! I will update the docs accordingly.

Just as a side note, if you are running these commands from within a virtual environment, you do not need to specify the '3' after either of those commands (you'd use `pip` and `python`, not `pip3` or `python3`). 
Whenever possible, create a new virtual environment and store dependencies there - helps with cross-bleeding of packages. Python's docs have [a good tutorial on how to use virtual environments](https://docs.python.org/3/tutorial/venv.html) that you can check out, or there are lots of good tutorials on YouTube!

**Comment by guenter-ms** [comment]
Hi, python3 works!

Now I have to study the concepts and define my use cases. Lets stay in contact if you like, For the time being: Thank you so much!

Take care, Guenter

Am 10.02.2021 um 20:10 schrieb Shane Sutro <notifications@github.com>:


Gotcha, we're getting closer!
I just verified on my own Raspberry Pi, and it's definitely to do with the whole Python 2 vs Python 3 thing.

That error you got is regarding that string format. Python's so-called "f-strings" are only supported in Python 3, and it looks like you're running it with Python 2. Just like you needed to specify pip3 instead of pip, you also need to call the script with python3 not python.
Make sure when you're running your file you specify that it should be run with Python 3 as follows:

pi@raspberrypi:~ $ python3 importapi.py

Thank you for bringing these to my attention! I will update the docs accordingly.

Just as a side note, if you are running these commands from within a virtual environment, you do not need to specify the '3' after either of those commands (you'd use pip and python, not pip3 or python3).
Whenever possible, create a new virtual environment and store dependencies there - helps with cross-bleeding of packages. Python's docs have a good tutorial on how to use virtual environments <https://docs.python.org/3/tutorial/venv.html> that you can check out, or there are lots of good tutorials on YouTube!

**Comment by SonicRift** [comment]
Glad to hear! I'm going to go ahead and close this. If you need anything else, feel free to shoot me an email!
